<a href="https://colab.research.google.com/github/Aleeza-GH/ML-learning-journey/blob/main/Random_Forest.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestClassifier

from sklearn.metrics import (
    accuracy_score,
    confusion_matrix,
    classification_report
)

In [2]:
df = pd.read_csv("/content/professional_customer_dataset.csv")

df.head()

,Age,YearsExperience,EducationLevel,CityTier,AnnualSalary,CreditScore,Purchased
0,22,0,High School,Tier-3,52276,439,0
1,54,28,Bachelor,Tier-2,158137,821,1
2,48,24,High School,Tier-3,113525,539,0
3,38,10,High School,Tier-2,72196,659,1
4,38,19,Bachelor,Tier-1,132959,684,1

In [3]:
df.shape

(1000, 7)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Age              1000 non-null   int64
 1   YearsExperience  1000 non-null   int64
 2   EducationLevel   1000 non-null   object
 3   CityTier         1000 non-null   object
 4   AnnualSalary     1000 non-null   int64
 5   CreditScore      1000 non-null   int64
 6   Purchased        1000 non-null   int64
dtypes: int64(5), object(2)
memory usage: 54.8+ KB

In [5]:
df.isnull().sum()

Age                0
YearsExperience    0
EducationLevel     0
CityTier           0
AnnualSalary       0
CreditScore        0
Purchased          0
dtype: int64

In [6]:
encoder = LabelEncoder()

df["EducationLevel"] = encoder.fit_transform(df["EducationLevel"])
df["CityTier"] = encoder.fit_transform(df["CityTier"])

df.head()

,Age,YearsExperience,EducationLevel,CityTier,AnnualSalary,CreditScore,Purchased
0,22,0,1,2,52276,439,0
1,54,28,0,1,158137,821,1
2,48,24,1,2,113525,539,0
3,38,10,1,1,72196,659,1
4,38,19,0,0,132959,684,1

In [7]:
X = df.drop("Purchased", axis=1)

y = df["Purchased"]

print(X.shape)
print(y.shape)

(1000, 6)
(1000,)

In [8]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

print(X_train.shape)
print(X_test.shape)

(800, 6)
(200, 6)

In [9]:
rf = RandomForestClassifier(
    n_estimators=100,
    random_state=42
)

rf.fit(X_train, y_train)

RandomForestClassifier(random_state=42)

In [10]:
y_pred = rf.predict(X_test)

y_pred[:10]

array([0, 1, 0, 0, 1, 1, 1, 1, 0, 1])

In [11]:
accuracy = accuracy_score(y_test, y_pred)

print("Accuracy:", accuracy)

Accuracy: 0.77

In [12]:
cm = confusion_matrix(y_test, y_pred)

print(cm)

[[ 49  21]
 [ 25 105]]

In [13]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.66      0.70      0.68        70
           1       0.83      0.81      0.82       130

    accuracy                           0.77       200
   macro avg       0.75      0.75      0.75       200
weighted avg       0.77      0.77      0.77       200

In [14]:
importance = pd.DataFrame({
    "Feature": X.columns,
    "Importance": rf.feature_importances_
})

importance.sort_values(
    by="Importance",
    ascending=False
)

           Feature  Importance
4     AnnualSalary    0.272527
5      CreditScore    0.216555
1  YearsExperience    0.210297
0              Age    0.157509
2   EducationLevel    0.107414
3         CityTier    0.035699