In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
df = pd.read_csv('/content/dataset-2.csv')

In [ ]:
df=df.iloc[:,:]

In [ ]:
df.sample(5)

    Age  Estimated Salary  Purchased
38   52             83000          1
24   41             87000          1
43   56             60000          1
39   53             48000          0
3    22             21000          0

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(df.drop('Purchased', axis=1), df['Purchased'], test_size=0.3, random_state=0)

X_train.shape, X_test.shape

((35, 2), (15, 2))

In [ ]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

scaler.fit(X_train)

x_train_scaled = scaler.transform(X_train)
x_test_scaled = scaler.transform(X_test)

In [ ]:
scaler.mean_

array([4.16571429e+01, 6.37142857e+04])

In [ ]:
X_train

    Age  Estimated Salary
7    28             55000
14   34             95000
45   58             32000
48   60             88000
29   45             82000
15   35             45000
30   46             71000
32   48             43000
16   35             88000
42   55             77000
20   38             92000
43   56             60000
8    29             77000
13   33             54000
25   42             75000
5    26             27000
17   36             76000
40   54             92000
49   61             39000
1    21             20000
12   33             72000
37   51             60000
24   41             87000
6    27             57000
23   41             45000
36   50             86000
21   39             99000
19   38             61000
9    30             37000
39   53             48000
46   58             84000
3    22             21000
0    19             19000
47   59             71000
44   57             95000

In [ ]:
x_train_scaled

array([[-1.10921294, -0.36812238],
       [-0.62190182,  1.32161969],
       [ 1.32734269, -1.33972407],
       [ 1.48977973,  1.02591483],
       [ 0.27150191,  0.77245352],
       [-0.5406833 , -0.7905579 ],
       [ 0.35272043,  0.30777445],
       [ 0.51515748, -0.875045  ],
       [-0.5406833 ,  1.02591483],
       [ 1.08368712,  0.56123576],
       [-0.29702773,  1.19488904],
       [ 1.16490564, -0.15690462],
       [-1.02799442,  0.56123576],
       [-0.70312034, -0.41036593],
       [ 0.02784635,  0.47674866],
       [-1.27164999, -1.55094183],
       [-0.45946478,  0.51899221],
       [ 1.0024686 ,  1.19488904],
       [ 1.57099825, -1.04401921],
       [-1.67774259, -1.84664669],
       [-0.70312034,  0.350018  ],
       [ 0.75881304, -0.15690462],
       [-0.05337217,  0.98367128],
       [-1.19043146, -0.28363528],
       [-0.05337217, -0.7905579 ],
       [ 0.67759452,  0.94142773],
       [-0.21580921,  1.4905939 ],
       [-0.29702773, -0.11466107],
       [-0.9467759 , -1.12850631],
       [ 0.92125008, -0.66382724],
       [ 1.32734269,  0.85694062],
       [-1.59652407, -1.80440314],
       [-1.84017963, -1.88889025],
       [ 1.40856121,  0.30777445],
       [ 1.24612416,  1.32161969]])